version: '3.8'
services:
  web:
    container_name: server_web
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver localhost:8000
    ports:
      - 8000:8000
