version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 13711371
    volumes:
      - ./sql/init.sh:/docker-entrypoint-initdb.d/init_CatOverflow.sh
    networks:
      my_network:
        ipv4_address: 172.28.0.2

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      my_network:
        ipv4_address: 172.28.0.3

  nginx_no_cache:
    image: nginx
    volumes:
      - ./conf.d/no_cache:/etc/nginx/conf.d
      - ./static:/catoverflow/static
      - ./uploads:/catoverflow/uploads
    ports:
      - "90:90"
    networks:
      my_network:
        ipv4_address: 172.28.0.6

  web_no_cache:
    depends_on:
      - db
      - adminer
      - nginx_no_cache
    container_name: server_web_no_cache
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_no_cache
    ports:
      - 8030:8030
    networks:
      my_network:
        ipv4_address: 172.28.0.9

  apache_benchmark:
    depends_on:
      - web_no_cache
    container_name: apache_benchmark
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_apache_benchmark
    command: tail -F /dev/null
    ports:
      - 8040:8040
    networks:
      my_network:
        ipv4_address: 172.28.0.8

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
