version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 13711371
    volumes:
      - ./sql/init.sh:/docker-entrypoint-initdb.d/init_CatOverflow.sh
    networks:
      my_network:
        ipv4_address: 172.28.0.2

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      my_network:
        ipv4_address: 172.28.0.3

  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./static:/catoverflow/static
      - ./uploads:/catoverflow/uploads
    ports:
      - "80:80"
#    environment:
#      - NGINX_HOST=catoverflow.com
#      - NGINX_PORT=80
    networks:
      my_network:
        ipv4_address: 172.28.0.4

  web:
    depends_on:
      - db
      - adminer
      - nginx
    container_name: server_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      my_network:
        ipv4_address: 172.28.0.5

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
