FROM python:3
RUN apt update -y && \
    apt install -y build-essential python-dev python3 python3-pip
RUN pip install --upgrade pip

RUN pip install uwsgi


ENV PYTHONUNBUFFERED 1

WORKDIR /app

ADD .. /app

EXPOSE 8081

CMD uwsgi --http :8081 --wsgi-file catoverflow_wsgi.py --master